### ISSUE TITLE
Error while compile

### ISSUE THREAD

**Issue by dj-fiorex** [esp32m/core#5]
Hello, thank you for this great piece of open source code, i have a problem building the basic example. I tried with three different version of esp-idf 5.1-rc2, 5.1 and master, but no success. 
This is the error:
```
[1030/1038] Building C object esp-idf/main/CMakeFiles/__idf_main.dir/app_main.c.obj
FAILED: esp-idf/main/CMakeFiles/__idf_main.dir/app_main.c.obj 
/Users/carmelofiorello/.espressif-51/tools/xtensa-esp32-elf/esp-12.2.0_20230208/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc -DCONFIG_ESP_TLS_SKIP_SERVER_CERT_VERIFY=y -DESP_PLATFORM -DIDF_VER=\"v5.1-rc2\" -DMBEDTLS_CONFIG_FILE=\"mbedtls/esp_config.h\" -DSOC_MMU_PAGE_SIZE=CONFIG_MMU_PAGE_SIZE -DUNITY_INCLUDE_CONFIG_H -D_GNU_SOURCE -D_POSIX_READER_WRITER_LOCKS -I/Users/carmelofiorello/EspIdfProjects/vs-esp-idf/build/config -I/Users/carmelofiorello/EspIdfProjects/vs-esp-idf/main -I/Users/carmelofiorello/esp-51/esp-idf/components/newlib/platform_include -I/Users/carmelofiorello/esp-51/esp-idf/components/freertos/FreeRTOS-Kernel/include -I/Users/carmelofiorello/esp-51/esp-idf/components/freertos/FreeRTOS-Kernel/portable/xtensa/include -I/Users/carmelofiorello/esp-51/esp-idf/components/freertos/esp_additions/include/freertos -I/Users/carmelofiorello/esp-51/esp-idf/components/freertos/esp_additions/include -I/Users/carmelofiorello/esp-51/esp-idf/components/freertos/esp_additions/arch/xtensa/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_hw_support/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_hw_support/include/soc -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_hw_support/include/soc/esp32 -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_hw_support/port/esp32/. -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_hw_support/port/esp32/private_include -I/Users/carmelofiorello/esp-51/esp-idf/components/heap/include -I/Users/carmelofiorello/esp-51/esp-idf/components/log/include -I/Users/carmelofiorello/esp-51/esp-idf/components/soc/include -I/Users/carmelofiorello/esp-51/esp-idf/components/soc/esp32 -I/Users/carmelofiorello/esp-51/esp-idf/components/soc/esp32/include -I/Users/carmelofiorello/esp-51/esp-idf/components/hal/esp32/include -I/Users/carmelofiorello/esp-51/esp-idf/components/hal/include -I/Users/carmelofiorello/esp-51/esp-idf/components/hal/platform_port/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_rom/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_rom/include/esp32 -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_rom/esp32 -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_common/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_system/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_system/port/soc -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_system/port/include/private -I/Users/carmelofiorello/esp-51/esp-idf/components/xtensa/include -I/Users/carmelofiorello/esp-51/esp-idf/components/xtensa/esp32/include -I/Users/carmelofiorello/esp-51/esp-idf/components/lwip/include -I/Users/carmelofiorello/esp-51/esp-idf/components/lwip/include/apps -I/Users/carmelofiorello/esp-51/esp-idf/components/lwip/include/apps/sntp -I/Users/carmelofiorello/esp-51/esp-idf/components/lwip/lwip/src/include -I/Users/carmelofiorello/esp-51/esp-idf/components/lwip/port/include -I/Users/carmelofiorello/esp-51/esp-idf/components/lwip/port/freertos/include -I/Users/carmelofiorello/esp-51/esp-idf/components/lwip/port/esp32xx/include -I/Users/carmelofiorello/esp-51/esp-idf/components/lwip/port/esp32xx/include/arch -I/Users/carmelofiorello/EspIdfProjects/vs-esp-idf/managed_components/esp32m/include -I/Users/carmelofiorello/esp-51/esp-idf/components/nvs_flash/include -I/Users/carmelofiorello/esp-51/esp-idf/components/spi_flash/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_partition/include -I/Users/carmelofiorello/esp-51/esp-idf/components/bootloader_support/include -I/Users/carmelofiorello/esp-51/esp-idf/components/bootloader_support/bootloader_flash/include -I/Users/carmelofiorello/esp-51/esp-idf/components/app_update/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_app_format/include -I/Users/carmelofiorello/esp-51/esp-idf/components/spiffs/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_http_client/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_event/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_https_ota/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_http_server/include -I/Users/carmelofiorello/esp-51/esp-idf/components/http_parser -I/Users/carmelofiorello/esp-51/esp-idf/components/console -I/Users/carmelofiorello/esp-51/esp-idf/components/vfs/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_wifi/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_wifi/wifi_apps/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_phy/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_phy/esp32/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_netif/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_adc/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_adc/interface -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_adc/esp32/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_adc/deprecated/include -I/Users/carmelofiorello/esp-51/esp-idf/components/mqtt/esp-mqtt/include -I/Users/carmelofiorello/esp-51/esp-idf/components/tcp_transport/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp-tls -I/Users/carmelofiorello/esp-51/esp-idf/components/esp-tls/esp-tls-crypto -I/Users/carmelofiorello/esp-51/esp-idf/components/mbedtls/port/include -I/Users/carmelofiorello/esp-51/esp-idf/components/mbedtls/mbedtls/include -I/Users/carmelofiorello/esp-51/esp-idf/components/mbedtls/mbedtls/library -I/Users/carmelofiorello/esp-51/esp-idf/components/mbedtls/esp_crt_bundle/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_timer/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/deprecated -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/analog_comparator/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/dac/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/gpio/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/gptimer/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/i2c/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/i2s/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/ledc/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/mcpwm/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/parlio/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/pcnt/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/rmt/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/sdio_slave/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/sdmmc/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/sigma_delta/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/spi/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/temperature_sensor/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/touch_sensor/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/twai/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/uart/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/usb_serial_jtag/include -I/Users/carmelofiorello/esp-51/esp-idf/components/driver/touch_sensor/esp32/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_pm/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_ringbuf/include -I/Users/carmelofiorello/esp-51/esp-idf/components/wpa_supplicant/include -I/Users/carmelofiorello/esp-51/esp-idf/components/wpa_supplicant/port/include -I/Users/carmelofiorello/esp-51/esp-idf/components/wpa_supplicant/esp_supplicant/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_eth/include -I/Users/carmelofiorello/EspIdfProjects/vs-esp-idf/managed_components/bblanchon__arduinojson/src -I/Users/carmelofiorello/esp-51/esp-idf/components/efuse/include -I/Users/carmelofiorello/esp-51/esp-idf/components/efuse/esp32/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_mm/include -I/Users/carmelofiorello/esp-51/esp-idf/components/pthread/include -I/Users/carmelofiorello/esp-51/esp-idf/components/app_trace/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_coex/include -I/Users/carmelofiorello/esp-51/esp-idf/components/unity/include -I/Users/carmelofiorello/esp-51/esp-idf/components/unity/unity/src -I/Users/carmelofiorello/esp-51/esp-idf/components/cmock/CMock/src -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_gdbstub/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_hid/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_psram/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_lcd/include -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_lcd/interface -I/Users/carmelofiorello/esp-51/esp-idf/components/protobuf-c/protobuf-c -I/Users/carmelofiorello/esp-51/esp-idf/components/protocomm/include/common -I/Users/carmelofiorello/esp-51/esp-idf/components/protocomm/include/security -I/Users/carmelofiorello/esp-51/esp-idf/components/protocomm/include/transports -I/Users/carmelofiorello/esp-51/esp-idf/components/esp_local_ctrl/include -I/Users/carmelofiorello/esp-51/esp-idf/components/espcoredump/include -I/Users/carmelofiorello/esp-51/esp-idf/components/espcoredump/include/port/xtensa -I/Users/carmelofiorello/esp-51/esp-idf/components/wear_levelling/include -I/Users/carmelofiorello/esp-51/esp-idf/components/sdmmc/include -I/Users/carmelofiorello/esp-51/esp-idf/components/fatfs/diskio -I/Users/carmelofiorello/esp-51/esp-idf/components/fatfs/vfs -I/Users/carmelofiorello/esp-51/esp-idf/components/fatfs/src -I/Users/carmelofiorello/esp-51/esp-idf/components/idf_test/include -I/Users/carmelofiorello/esp-51/esp-idf/components/idf_test/include/esp32 -I/Users/carmelofiorello/esp-51/esp-idf/components/ieee802154/include -I/Users/carmelofiorello/esp-51/esp-idf/components/json/cJSON -I/Users/carmelofiorello/esp-51/esp-idf/components/perfmon/include -I/Users/carmelofiorello/esp-51/esp-idf/components/wifi_provisioning/include -I/Users/carmelofiorello/EspIdfProjects/vs-esp-idf/managed_components/espressif__esp-modbus/freemodbus/common/include -I/Users/carmelofiorello/EspIdfProjects/vs-esp-idf/managed_components/espressif__mdns/include -I/Users/carmelofiorello/EspIdfProjects/vs-esp-idf/managed_components/joltwallet__littlefs/include -I/Users/carmelofiorello/EspIdfProjects/vs-esp-idf/build/web-ui -mlongcalls -Wno-frame-address  -fdiagnostics-color=always -ffunction-sections -fdata-sections -Wall -Werror=all -Wno-error=unused-function -Wno-error=unused-variable -Wno-error=unused-but-set-variable -Wno-error=deprecated-declarations -Wextra -Wno-unused-parameter -Wno-sign-compare -Wno-enum-conversion -gdwarf-4 -ggdb -Og -fmacro-prefix-map=/Users/carmelofiorello/EspIdfProjects/vs-esp-idf=. -fmacro-prefix-map=/Users/carmelofiorello/esp-51/esp-idf=/IDF -fstrict-volatile-bitfields -fno-jump-tables -fno-tree-switch-conversion -DconfigENABLE_FREERTOS_DEBUG_OCDAWARE=1 -std=gnu17 -Wno-old-style-declaration -MD -MT esp-idf/main/CMakeFiles/__idf_main.dir/app_main.c.obj -MF esp-idf/main/CMakeFiles/__idf_main.dir/app_main.c.obj.d -o esp-idf/main/CMakeFiles/__idf_main.dir/app_main.c.obj -c /Users/carmelofiorello/EspIdfProjects/vs-esp-idf/main/app_main.c
In file included from /Users/carmelofiorello/EspIdfProjects/vs-esp-idf/main/app_main.c:1:
/Users/carmelofiorello/EspIdfProjects/vs-esp-idf/managed_components/esp32m/include/esp32m/app.hpp:5:10: fatal error: memory: No such file or directory
    5 | #include <memory>
      |          ^~~~~~~~
compilation terminated.
[1031/1038] Building ASM object esp-idf/web-ui/CMakeFiles/__idf_web-ui.dir/__/__/web-ui/dist/main.js.S.obj
ninja: build stopped: subcommand failed.
```

i can't understand what am i doing wrong, i'm on Mac M2, esp-idf installed through the vs-code extension.

Can you help me?
Thanks!

p.s. i also sent you an email

**Comment by dyarkovoy** [comment]
Hello, @dj-fiorex. 
We use Linux and Windows for development, never tried to compile on Mac. 
In fact, we don't even have any Macs around to try, unfortunately. 
I will try to install Mac OS emulator to check what could the problem be, and will let you know

**Comment by dj-fiorex** [comment]
Don't worry, i have another machine with windows to try, i will let you know

Meanwhile please take a moment to reply to my email, thanks

**Comment by dyarkovoy** [comment]
Sounds good. 
Still, need to check this Mac issue and will report here. 
Frankly, I assumed there would be no problem with Macs if it compiles on Windows and Linux, the assumption was wrong and the problem needs to be fixed in any case.
I replied to your E-mail, sorry for the delay, it went to my spam and I didn't notice it right away.

**Comment by dj-fiorex** [comment]
Just tried on windows with esp-idf v.5.1 and it works, i can successfully build for esp32.
My project is based on the esp32-s3 version, i think i can't change the target to esp32-s3 because esp32m uses bluetooth classic that is not available on the esp32-s3 that has BLE 5.0. Can you suggest me a way to be able to configure the project to use classic bluetooth or ble based on the target? I'm really not so expert with esp-idf or cmake . i will then implement the same functionality of the classic bluetooth using the new ble stack :)
Thanks

**Comment by dyarkovoy** [comment]
It is being used with s3 chip in of the projects, so should not be a problem. 
Do you get an error trying to compile for esp32-s3? Can you post the text of the error?
Edit:
You need to use esp-idf master branch, it will not compile with 5.1, 5.2 or any other stable branches.

**Comment by dj-fiorex** [comment]
so sorry for the misunderstanding but let's recap what i did
1. Clone your repo
2. cd examples/basic
3. idf.py set-target esp32s3
and i received this warning and the target does not change
```
 idf.py.exe set-target esp32s3
C:\Users\carme\esp\esp-idf\tools\check_python_dependencies.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Adding "set-target"'s dependency "fullclean" to list of commands with default set of options.
Executing action: fullclean
Build directory 'C:\Users\carme\Documents\TEST\esp-idf\core\examples\basic\build' not found. Nothing to clean.
Executing action: set-target
Set Target to: esp32s3, new sdkconfig will be created.
Target 'esp32s3' specified on command line is not consistent with target 'esp32' in the environment.
```
EDIT:
i can confirm that it successfully build with release/5.1 branch and esp32 target

**Comment by dyarkovoy** [comment]
Try this 
1. clone repo
2. cd `examples/basic`
3. add this line to the file `sdkconfig.defaults`:
`CONFIG_IDF_TARGET="esp32s3"`
4. make sure the file `sdkconfig` does not exist, if it does - remove it.
5. `idf.py build`

**Comment by dj-fiorex** [comment]
just tried but no success. i can successfully build but the target remain esp32
```
webpack 5.88.0 compiled successfully in 18992 ms
[1038/1039] Generating binary image from built executableesptool.py v4.6.2
Creating esp32 image...
Merged 25 ELF sections
Successfully created esp32 image.
Generated C:/Users/carme/Documents/TEST/esp-idf/core/examples/basic/build/basic.bin
[1039/1039] cmd.exe /C "cd /D C:\Users\carme\Documents\TEST\esp-idf\core\examples\basic\buil...rtition-table.bin C:/Users/carme/Documents/TEST/esp-idf/core/examples/basic/build/basic.bin"basic.bin binary size 0x157d20 bytes. Smallest app partition is 0x1f0000 bytes. 0x982e0 bytes (31%) free.

Project build complete. To flash, run this command:
C:\Users\carme\.espressif\python_env\idf5.1_py3.8_env\Scripts\python.exe ..\..\..\..\..\..\esp\esp-idf\components\esptool_py\esptool\esptool.py -p (PORT) -b 460800 --before default_reset --after hard_reset --chip esp32  write_flash --flash_mode dio --flash_size 4MB --flash_freq 40m 0x1000 build\bootloader\bootloader.bin 0x8000 build\partition_table\partition-table.bin 0xd000 build\ota_data_initial.bin 0x10000 build\basic.bin
or run 'idf.py -p (PORT) flash'
PS C:\Users\carme\Documents\TEST\esp-idf\core\examples\basic> idf.py flash
C:\Users\carme\esp\esp-idf\tools\check_python_dependencies.py:12: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
Executing action: flash
Serial port COM3
Connecting....
Detecting chip type... ESP32-S3
Running ninja in directory C:\Users\carme\Documents\TEST\esp-idf\core\examples\basic\build
Executing "ninja flash"...
[1/6] Performing build step for 'bootloader'
[1/1] cmd.exe /C "cd /D C:\Users\carme\Documents\TEST\esp-idf\core\examples\basic\build\bootloader\esp-idf\esptool_py && C:\Users\carme\.espressif\python_env\idf5.1_py3.8_env\Scripts\python.exe C:/Users/carme/esp/esp-idf/components/partition_table/check_sizes.py --offset 0x8000 bootloader 0x1000 C:/Users/carme/Documents/TEST/esp-idf/core/examples/basic/build/bootloader/bootloader.bin"
Bootloader binary size 0x5fc0 bytes. 0x1040 bytes (15%) free.
[2/4] Generating dist/index.html.S, dist/main.js.S
esp32m-ui:INFO:using yarn executable C:\Program Files\nodejs\yarn.CMD
esp32m-ui:INFO:linking C:/Users/carme/Documents/TEST/esp-idf/core/examples/basic/build\web-ui to C:/Users/carme/Documents/TEST/esp-idf/core/examples/basic/managed_components/esp32m\web-ui 
 YN0000:  Resolution step
 YN0032:  cpu-features@npm:0.0.8: Implicit dependencies on node-gyp are discouraged
 YN0000:  Completed in 3s 113ms
 YN0000:  Fetch step
 YN0013:  @babel/code-frame@npm:7.22.5 can't be found in the cache and will be fetched from the remote registry
 YN0013:  @babel/compat-data@npm:7.22.5 can't be found in the cache and will be fetched from the remote registry
 ..... Omitted for brevity ......
 YN0000: Done with warnings in 3s 798ms
esp32m-ui:INFO:building C:/Users/carme/Documents/TEST/esp-idf/core/examples/basic/build\web-ui
`isModuleDeclaration` has been deprecated, please migrate to `isImportOrExportDeclaration`
    at isModuleDeclaration (C:\Users\carme\Documents\TEST\esp-idf\core\examples\basic\build\web-ui\node_modules\babel-plugin-lodash\node_modules\@babel\types\lib\validators\generated\index.js:2794:35)
    at PluginPass.Program (C:\Users\carme\Documents\TEST\esp-idf\core\examples\basic\build\web-ui\node_modules\babel-plugin-lodash\lib\index.js:102:44)
asset main.js 810 KiB [emitted] [minimized] (name: main) 2 related assets
asset index.html 443 bytes [emitted] 1 related asset
orphan modules 9.37 MiB [orphan] 12237 modules
runtime modules 2.25 KiB 6 modules
cacheable modules 2.33 MiB
  modules by path ./node_modules/ 166 KiB
    modules by path ./node_modules/react/ 7.98 KiB 4 modules
    modules by path ./node_modules/use-sync-external-store/ 2.59 KiB 4 modules
    modules by path ./node_modules/react-dom/ 131 KiB 3 modules
    modules by path ./node_modules/redux-persist/ 2.5 KiB 3 modules
    modules by path ./node_modules/react-is/ 2.4 KiB 2 modules
    modules by path ./node_modules/scheduler/ 4.33 KiB 2 modules
    + 7 modules
  ./src/index.ts + 697 modules 2.17 MiB [built] [code generated]
  node-localstorage (ignored) 15 bytes [built] [code generated]
webpack 5.88.0 compiled successfully in 13956 ms
[3/4] cmd.exe /C "cd /D C:\Users\carme\Documents\TEST\esp-idf\core\examples\basic\build\esp-idf\esptool_py && C:\Users\carme\.espressif\python_env\idf5.1_py3.8_env\Scripts\python.exe C:/Users/carme/esp/esp-idf/components/partition_table/check_sizes.py --offset 0x8000 partition --type app C:/Users/carme/Documents/TEST/esp-idf/core/examples/basic/build/partition_table/partition-table.bin C:/Users/carme/Documents/TEST/esp-idf/core/examples/basic/build/basic.bin"
basic.bin binary size 0x157d20 bytes. Smallest app partition is 0x1f0000 bytes. 0x982e0 bytes (31%) free.
[3/4] cmd.exe /C "cd /D C:\Users\carme\esp\esp-idf\components\esptool_py && C:\Users\carme\.espressif\tools\cmake\3.24.0\bin\cmake.exe -D IDF_PATH=C:/Users/carme/esp/esp-idf -D SERIAL_TOOL=C:/Users/carme/.espressif/python_env/idf5.1_py3.8_env/Scripts/python.exe;;C:/Users/carme/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32 -D SERIAL_TOOL_ARGS=--before=default_reset;--after=hard_reset;write_flash;@flash_args -D WORKING_DIRECTORY=C:/Users/carme/Documents/TEST/esp-idf/core/examples/basic/build -P C:/Users/carme/esp/esp-idf/components/esptool_py/run_serial_tool.cmake"
esptool esp32 -p COM3 -b 460800 --before=default_reset --after=hard_reset write_flash --flash_mode dio --flash_freq 40m --flash_size 4MB 0x1000 bootloader/bootloader.bin 0x10000 basic.bin 0x8000 partition_table/partition-table.bin 0xd000 ota_data_initial.bin
esptool.py v4.6.2
Serial port COM3
Connecting....

A fatal error occurred: This chip is ESP32-S3 not ESP32. Wrong --chip argument?
CMake Error at run_serial_tool.cmake:66 (message):

  C:/Users/carme/.espressif/python_env/idf5.1_py3.8_env/Scripts/python.exe;;C:/Users/carme/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32
  failed.



FAILED: CMakeFiles/flash C:/Users/carme/Documents/TEST/esp-idf/core/examples/basic/build/CMakeFiles/flash 
cmd.exe /C "cd /D C:\Users\carme\esp\esp-idf\components\esptool_py && C:\Users\carme\.espressif\tools\cmake\3.24.0\bin\cmake.exe -D IDF_PATH=C:/Users/carme/esp/esp-idf -D SERIAL_TOOL=C:/Users/carme/.espressif/python_env/idf5.1_py3.8_env/Scripts/python.exe;;C:/Users/carme/esp/esp-idf/components/esptool_py/esptool/esptool.py;--chip;esp32 -D SERIAL_TOOL_ARGS=--before=default_reset;--after=hard_reset;write_flash;@flash_args -D WORKING_DIRECTORY=C:/Users/carme/Documents/TEST/esp-idf/core/examples/basic/build -P C:/Users/carme/esp/esp-idf/components/esptool_py/run_serial_tool.cmake"      
ninja: build stopped: subcommand failed.
ninja failed with exit code 1, output of the command is in the C:\Users\carme\Documents\TEST\esp-idf\core\examples\basic\build\log\idf_py_stderr_output_13416 and C:\Users\carme\Documents\TEST\esp-idf\core\examples\basic\build\log\idf_py_stdout_output_13416
```

EDIT: if i try to flash manually the image i will receive thi error message:
```
PS C:\Users\carme\Documents\TEST\esp-idf\core\examples\basic> C:\Users\carme\.espressif\python_env\idf5.1_py3.8_env\Scripts\python.exe ..\..\..\..\..\..\esp\esp-idf\components\esptool_py\esptool\esptool.py -p COM3 -b 460800 --before default_reset --after hard_reset --chip esp32s3  write_flash --flash_mode dio --flash_size 4MB --flash_freq 40m 0x1000 build\bootloader\bootloader.bin 0x8000 build\partition_table\partition-table.bin 0xd000 build\ota_data_initial.bin 0x10000 build\basic.bin  
esptool.py v4.6.2
Serial port COM3
Connecting....
Chip is ESP32-S3 (revision v0.1)
Features: WiFi, BLE
Crystal is 40MHz
MAC: f4:12:fa:43:72:9c
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 460800
Changed.
Configuring flash size...
Unexpected chip id in image. Expected 9 but value was 0. Is this image for a different chip model?

A fatal error occurred: build\bootloader\bootloader.bin is not an ESP32-S3 image. Use --force to flash anyway.
PS C:\Users\carme\Documents\TEST\esp-idf\core\examples\basic> 
```

**Comment by dyarkovoy** [comment]
Ok, I think it is because you already built the project for esp32 target. In this case, switching to another target is tricky, even `fullclean` doesn't help, you need to remove some other files like `dependencies.lock` and maybe others, I don't rember exactly right now.
But if you delete everything, do fresh clone and follow the steps from my previous answer, it should build properly. Please see if this works for you.

**Comment by dj-fiorex** [comment]
ok, now it works, maybe the vscode extension interference was the problem. Anyway i just flashed and configure wifi network by ui, need to going to page /wifi typing in the url bar because i don't see any sidebar. i see from the logs that the esp32 is connected and the ip address is shown but if i go to the ip address the page will not load and from the logs i see this:
```
0:00:11:09.287 W wifi  [ADDBA]rx delba, code:37, delete tid:3
0:00:11:10.659 I wifi  my IP: 192.168.1.82
0:00:11:10.689 I WIFI_STA_DEF  connecting -> connected
2023-06-23 16:05:50.821 D sntp  local time/date was set to 2023-06-23 16:05:50, (TZ=)
2023-06-23 16:05:58.041 I wifi  scan started
2023-06-23 16:06:05.030 W wifi  [ADDBA]rx delba, code:37, delete tid:5
2023-06-23 16:06:22.475 W system  (704725) httpd_uri: httpd_uri: Method '3' not allowed for URI '/chat'
2023-06-23 16:06:22.475 W system  (704725) httpd_txrx: httpd_resp_send_err: 405 Method Not Allowed - Specified method is invalid for this resource
2023-06-23 16:06:31.054 I wifi  scan started
2023-06-23 16:06:36.277 W system  (718525) httpd_uri: httpd_uri: Method '3' not allowed for URI '/chat'
2023-06-23 16:06:36.277 W system  (718525) httpd_txrx: httpd_resp_send_err: 405 Method Not Allowed - Specified method is invalid for this resource
2023-06-23 16:07:04.439 I wifi  scan started
2023-06-23 16:07:37.220 W system  (779475) httpd_uri: httpd_uri: Method '3' not allowed for URI '/chat'
2023-06-23 16:07:37.220 W system  (779475) httpd_txrx: httpd_resp_send_err: 405 Method Not Allowed - Specified method is invalid for this resource
2023-06-23 16:07:37.430 I wifi  scan started
2023-06-23 16:07:57.287 W system  (799535) httpd_uri: httpd_uri: Method '3' not allowed for URI '/chat'
2023-06-23 16:07:57.287 W system  (799535) httpd_txrx: httpd_resp_send_err: 405 Method Not Allowed - Specified method is invalid for this resource
2023-06-23 16:08:10.569 I wifi  scan started
2023-06-23 16:08:43.580 I wifi  scan started
2023-06-23 16:08:58.222 W system  (860475) httpd_uri: httpd_uri: Method '3' not allowed for URI '/chat'
2023-06-23 16:08:58.222 W system  (860475) httpd_txrx: httpd_resp_send_err: 405 Method Not Allowed - Specified method is invalid for this resource
2023-06-23 16:09:16.711 I wifi  scan started
2023-06-23 16:09:21.034 W wifi  [ADDBA]rx delba, code:37, delete tid:3
2023-06-23 16:10:06.216 W system  (928465) httpd_uri: httpd_uri: Method '3' not allowed for URI '/chat'
2023-06-23 16:10:06.216 W system  (928465) httpd_txrx: httpd_resp_send_err: 405 Method Not Allowed - Specified method is invalid for this resource
2023-06-23 16:10:49.726 W wifi  [ADDBA]rx delba, code:37, delete tid:7
2023-06-23 16:11:19.729 W system  (1001985) httpd_txrx: httpd_sock_err: error in recv : 104
2023-06-23 16:11:19.729 W system  (1001985) httpd_ws: httpd_ws_get_frame_type: Failed to read header byte (socket FD invalid), closing socket now
2023-06-23 16:11:19.731 D ui-http-54  session closed
2023-06-23 16:18:35.979 W wifi  inactive timer: now=55a69020 last_rx_time=43bdfe07 diff=495a6, aid[1]de:5e:ab:c5:f3:b3 leave
2023-06-23 16:19:34.538 W WIFI_AP_DEF  disabling AP because STA is connected
2023-06-23 16:19:34.538 I wifi  changing mode: AP+STA -> STA
2023-06-23 16:19:34.540 I WIFI_AP_DEF  running -> stopped
2023-06-23 16:19:34.638 I WIFI_AP_DEF  stopped -> initial
2023-06-23 16:21:05.014 W wifi  [ADDBA]rx delba, code:37, delete tid:3
2023-06-23 16:37:57.504 W wifi  [ADDBA]rx delba, code:37, delete tid:7
2023-06-23 16:38:00.645 W wifi  [ADDBA]rx delba, code:37, delete tid:3
2023-06-23 16:38:00.679 W wifi  [ADDBA]rx delba, code:37, delete tid:4
2023-06-23 16:38:02.744 W wifi  [ADDBA]rx delba, code:37, delete tid:2
2023-06-23 16:38:02.754 W wifi  [ADDBA]rx delba, code:37, delete tid:6
2023-06-23 16:38:03.949 W wifi  [ADDBA]rx delba, code:37, delete tid:5
2023-06-23 16:40:31.954 W wifi  [ADDBA]rx delba, code:37, delete tid:5
2023-06-23 16:40:31.978 W wifi  [ADDBA]rx delba, code:37, delete tid:3
ESP_ERROR_CHECK_WITHOUT_ABORT failed: esp_err_t 0xb006 (ESP_ERR_HTTPD_RESP_SEND) at 0x42018f41
0x42018f41: esp32m::ui::Httpd::incomingReq(httpd_req*) at C:/Users/carme/Documents/TEST/esp-idf/core/examples/basic/managed_components/esp32m/src/ui/httpd.cpp:163 (discriminator 1)

file: "./managed_components/esp32m/src/ui/httpd.cpp" line 163
func: esp_err_t esp32m::ui::Httpd::incomingReq(httpd_req_t*)
expression: httpd_resp_send( req, (const char *)found->_start, found->_end - found->_start)
2023-06-23 16:41:14.438 W system  (2796695) httpd_txrx: httpd_sock_err: error in send : 11
2023-06-23 16:41:37.017 W wifi  [ADDBA]rx delba, code:37, delete tid:4
2023-06-23 16:41:38.076 W wifi  [ADDBA]rx delba, code:37, delete tid:3
2023-06-23 16:41:57.857 W wifi  [ADDBA]rx delba, code:37, delete tid:5

```
EDIT:
i think it was a problem with my router, now it works good. i will test it and then i will reply to your mail. Thanks again
